
version: 2

models:
  - name: stg_superheroes
    description: Demographics about each superhero such as name, hair color, height and weight. 
    columns:
      - name: name
        tests:
          - not_null
      - name: height
        tests:
          - positive_values
      - name: weight
        tests:
          - positive_values

  - name: stg_addresses
    description: addresses of customer orders
    columns:
      - name: address_id
        tests:
          - not_null
      - name: address
        tests:
          - not_null
      - name: zipcode
        tests:
          - not_null

  - name: stg_users
    description: details of users 
    columns:
      - name: user_id
        tests:
          - not_null
      - name: first_name
        tests:
          - not_null
      - name: last_name
        tests:
          - not_null
      - name: email
        tests:
          - not_null
      - name: phone_number
        tests:
          - not_null
      - name: created_at
        tests:
          - not_null
      - name: updated_at
        tests:
          - not_null
      - name: address_id
        tests:
          - not_null

  - name: stg_events
    description: understand each user's events by page and product.
    columns:
      - name: event_id
        tests:
          - not_null
          - unique
      - name: user_id
        tests:
          - not_null
      - name: event_type
        tests:
          - not_null
      - name: page_url
      - name: created_at_utc
        tests:
          - not_null
      - name: order_id
      - name: product_id

  - name: stg_order_items
    description: Details about each order
    columns:
      - name: order_id
        tests:
          - not_null
      - name: product_id
        tests:
          - not_null
      - name: total_order_items
        tests:
          - positive_values
  
  - name: stg_orders
    description: detailed log of orders
    columns:
      - name: order_id
        tests:
          - not_null
          - unique
      - name: promo_id
      - name: user_id
        tests:
          - not_null
      - name: address_id
        tests:
          - not_null
      - name: created_at
      - name: order_cost
      - name: shipping_cost
      - name: tracking_id
      - name: shipping_service
      - name: estimated_delivery
      - name: delivered
      - name: status
  
  - name: stg_products
    description: product information
    columns:
      - name: product_id
        tests:
          - not_null
          - unique
      - name: product_name
        tests:
          - not_null
      - name: price_usd
        tests:
          - positive_values
      - name: total_inventory
        tests: 
          - not_null

  - name: stg_promos
    description: details on various promotions.
    columns:
      - name: promo_id
        tests:
          - not_null
          - unique
      - name: price_discount_rate
        tests:
          - positive_values
      - name: status
        tests: 
          - not_null